site_name: isq
site_description: A system for representing physical units
repo_name: cathaypacific8747/isq
repo_url: https://github.com/cathaypacific8747/isq
site_url: https://cathaypacific8747.github.io/isq/
nav:
  - Home: "README.md"
  - API Reference:
    - Core: "api/core.md"
    - SI units: "api/si.md"
    - U.S. Customary units: "api/us_customary.md"
    - Aerospace: "api/aerospace.md"

theme:
  name: material
  features:
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.annotate
    - navigation.expand
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github
plugins:
  - search
  - social
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          inventories:
            - https://docs.python.org/3/objects.inv
            - https://numpy.org/doc/stable/objects.inv
          options:
            # NOTE: bug in upstream, with `annotations_path: brief` top level SI unit definitions like `(KG * M * S**-2).alias("newton")` gets incorrectly rendered as `.alias("newton")`
            # https://github.com/mkdocstrings/python/blob/bac553d8bd87c2ca9a1cd67fc473e2686a4eedc2/src/mkdocstrings_handlers/python/templates/material/_base/expression.html.jinja#L92
            # this should have the check ` and expression.first.classname in ("ExprName", "ExprAttribute")`
            annotations_path: source # temporary fix
            inherited_members: true
            members_order: source
            separate_signature: true
            show_signature_annotations: true
            merge_init_into_class: true
            docstring_section_style: table
            signature_crossrefs: true
            show_if_no_docstring: true
            show_submodules: false
            show_source: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            show_root_heading: true
            show_root_full_path: false
            docstring_style: sphinx
            group_by_category: false
      enable_inventory: true
markdown_extensions:
  - abbr
  - attr_list
  - admonition
  - footnotes
  - md_in_html
  - pymdownx.details
  - pymdownx.blocks.tab:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      pygments_lang_class: true
  - pymdownx.inlinehilite:
      style_plain_text: py3
  - pymdownx.magiclink
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: "¤"
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - assets/js/katex.js
  - https://cdn.jsdelivr.net/npm/katex@0.16.22/dist/katex.min.js
  - https://cdn.jsdelivr.net/npm/katex@0.16.22/dist/contrib/auto-render.min.js

extra_css:
  - https://cdn.jsdelivr.net/npm/katex@0.16.22/dist/katex.min.css