"""A `griffe` extension to dynamically collect `isqx` definitions/details.

[Details][isqx.details.Details] are injected into the docstrings of attributes
and functions in the documentation generated by `mkdocstrings-python`.

!!! note

    You must install `isqx` with the `docs` extra optional dependencies
    to use this module.
"""

from __future__ import annotations

import ast
import inspect
import json
from collections.abc import Mapping
from dataclasses import asdict, dataclass, field, replace
from pathlib import Path
from typing import TYPE_CHECKING, Any, Callable, NamedTuple, TypeVar

from griffe import (
    Alias,
    Docstring,
    Extension,
    GriffeLoader,
    Inspector,
    Object,
    ObjectNode,
    Visitor,
    dynamic_import,
    get_logger,
    load_extensions,
)
from griffe._internal.expressions import (
    Expr,
    ExprAttribute,
    ExprCall,
    ExprDict,
    ExprKeyword,
    ExprName,
    ExprSubscript,
    ExprTuple,
)
from griffe._internal.models import Attribute
from typing_extensions import TypeAlias, TypeGuard

from .. import (
    Anchor,
    Dimensionless,
    LazyProduct,
    QtyKind,
    Scaled,
    StrFragment,
    Tagged,
    module_attribute_metadata,
)
from .. import (
    Expr as IsqxExpr,
)
from .._core import _ARGS_EXPR, _ARGS_NUMBER
from ..details import (
    _ARGS_DETAIL_KEY,
    Equation,
    HasKaTeXWhere,
    Symbol,
    Wikidata,
    _RefSelf,
)
from . import PATH_PLUGIN
from .unit_json import (
    UnitExprJson,
    UnitRegistry,
    build_unit_decl_table,
    serialize_unit_decls,
    serialize_unit_expr,
)

if TYPE_CHECKING:
    from typing import Generator

    from griffe import Module
    from griffe._internal.models import Attribute

    from .. import AnnotatedMetadata, Number
    from ..details import Detail, DetailKey, Details, WhereValue


logger = get_logger(__name__)


@dataclass(frozen=True)
class IsqxExtensionConfig:
    definitions: tuple[str, ...] = ()
    details: tuple[str, ...] = ()


def get_templates_path() -> Path:
    """See: https://mkdocstrings.github.io/usage/handlers/#handler-extensions"""
    return PATH_PLUGIN / "templates"


_ARGS_DEFINITION = (LazyProduct, *_ARGS_NUMBER, *_ARGS_EXPR, QtyKind)
# NOTE: equilibrium constants are factory functions that return a QtyKind.
# right now we skip over them!


# see: https://mkdocstrings.github.io/griffe/guide/users/how-to/selectively-inspect/
@dataclass(frozen=True)
class Where:
    symbol: str
    description: StrFragment | tuple[StrFragment, ...]
    # some where-clause entries are pure prose or Anchors, so it can be None
    unit: UnitExprJson | None


@dataclass(frozen=True)
class KaTeXWhere:
    katex: str
    where: tuple[Where, ...] | None = None


@dataclass(frozen=True)
class SymbolDetail(KaTeXWhere):
    remarks: str | None = None


@dataclass(frozen=True)
class EquationDetail(KaTeXWhere):
    assumptions: tuple[StrFragment | tuple[StrFragment, ...], ...] | None = None


@dataclass(frozen=True)
class WikidataDetail:
    qcode: str


@dataclass(frozen=True)
class Quantity:
    value: str  # for now: in the future we should support lazy products
    # constants that make it into objects.json have already passed annotated
    # unit validation in write_objects, so this payload is always present.
    unit: UnitExprJson


DefinitionPath: TypeAlias = str
PublicApiPath: TypeAlias = str


@dataclass
class QtyKindDetail:
    """Several quantities can share the same unit. Two cases:

    - Explicit inheritance: when a quantity is defined by subscripting
        another, like `POTENTIAL_ENERGY = ENERGY["potential"]`: this is a
        strong signal of a parent-child relationship.
        we can detect this during the griffe AST walking
    - Implicit grouping: some quantities are related by their physical
        dimension but not defined via subscripting (e.g., SPEED and VELOCITY).
        we can group them by their underlying SI dimension.
        the hierarchy can be inferred from the tags.
    """

    parent: str | None = None
    # details are accumulated before we know whether a path resolves to a
    # QtyKind definition, so keeping it optional at staging-model
    unit_si_coherent: UnitExprJson | None = None
    tags: tuple[str, ...] = field(default_factory=tuple)  # str for now
    wikidata: list[WikidataDetail] = field(default_factory=list)
    symbols: list[SymbolDetail] = field(default_factory=list)
    equations: list[EquationDetail] = field(default_factory=list)


class IsqxExtension(Extension):
    def __init__(
        self,
        config: Mapping[str, Any] | None = None,
    ):
        self.config = (
            IsqxExtensionConfig(
                definitions=tuple(config.get("definitions", ())),
                details=tuple(config.get("details", ())),
            )
            if config is not None
            else IsqxExtensionConfig()
        )
        self.definitions: Definitions = {}
        self.objects: dict[str, QtyKindDetail] = {}  # by path
        self.possible_parent_maps: dict[str, str] = {}  # child -> parent
        """Note that items in this map are not guaranteed to be isqx objects
        because griffe works with static analysis."""
        self.alias_targets: dict[PublicApiPath, DefinitionPath] = {}
        self.public_api_candidates: dict[
            DefinitionPath, set[PublicApiPath]
        ] = {}

    def on_instance(
        self,
        *,
        node: ast.AST | ObjectNode,
        obj: Object,
        agent: Visitor | Inspector,
        **kwargs: Any,
    ) -> None:
        inject_citation_into_docstring(obj, agent)

        # collect strict parent-child relationships
        if (
            isinstance(obj, Attribute)
            and isinstance(obj.value, ExprSubscript)
            and isinstance(
                parent_expr := obj.value.left, (ExprName, ExprAttribute)
            )
        ):
            parent_path = parent_expr.canonical_path
            if parent_path.split(".", 1)[0] in ("typing", "typing_extensions"):
                # heuristic: we captured something invalid like Union[str, int]
                return
            self.possible_parent_maps[obj.canonical_path] = parent_path

    def on_module_instance(
        self,
        *,
        node: ast.AST | ObjectNode,
        mod: Module,
        agent: Visitor | Inspector,
        **kwargs: Any,
    ) -> None:
        """Populate definitions from the current module being visited using
        runtime analysis, if it is matches the path under the configured
        definitions list.

        Note that if module `a` contains `FOO: Annotated[float, isqx.M] = 1.0`
        and module `b` contains `from a import FOO`, then `self.definitions`
        will contain both (which points to the same object):

        - `a.FOO`: Definition(value=1.0, annotated_metadata=M)
        - `b.FOO`: Definition(value=1.0, annotated_metadata=None)

        which is not ideal. When `griffe` visits `b`, `on_alias` will make sure
        the definition for `b.FOO` is removed.
        """
        if mod.path not in self.config.definitions:
            return
        module_rt = dynamic_import(mod.path)
        metadata = dict(module_attribute_metadata(module_rt))
        self.definitions |= {
            f"{mod.path}.{name}": Definition(obj, metadata.get(name))
            for name, obj in inspect.getmembers(module_rt)
            if isinstance(obj, _ARGS_DEFINITION)
        }

    def on_alias_instance(
        self,
        *,
        node: ast.AST | ObjectNode,
        alias: Alias,
        agent: Visitor | Inspector,
        **kwargs: Any,
    ) -> None:
        target_path = _get_alias_definition_path(alias)
        if target_path is not None:
            _register_public_api_candidate(
                alias.path,
                target_path,
                alias_targets=self.alias_targets,
                public_api_candidates=self.public_api_candidates,
            )
        # todo: actually we probably shouldn't do this
        if alias.path in self.definitions:
            del self.definitions[alias.path]

    def on_package(
        self, *, pkg: Module, loader: GriffeLoader, **kwargs: Any
    ) -> None:
        _collect_alias_candidates(
            pkg_path=pkg.path,
            modules_collection=loader.modules_collection,
            alias_targets=self.alias_targets,
            public_api_candidates=self.public_api_candidates,
        )
        logger.info(f"loaded {len(self.definitions)} definitions")
        path_resolver = _PathResolver(
            alias_targets=self.alias_targets,
            public_api_candidates=self.public_api_candidates,
        )
        public_definitions = _build_public_unit_paths(
            self.definitions,
            path_resolver,
        )
        unit_decls = build_unit_decl_table(
            {
                path: definition.value
                for path, definition in self.definitions.items()
                if isinstance(definition.value, _ARGS_EXPR)
            },
            public_definitions=public_definitions,
        )
        serialized_units = serialize_unit_decls(unit_decls=unit_decls)

        for defs_path in self.config.details:
            for path, item in _process_details_module(
                defs_path,
                loader,
                self.definitions,
                path_resolver,
                unit_decls,
            ):
                objects = self.objects.setdefault(path, QtyKindDetail())
                attr_target: Attribute = loader.modules_collection[path]
                isqx_extras = _get_or_init_isqx_extras(attr_target)
                isqx_extras["units"] = serialized_units

                if isinstance(item, WikidataDetail):
                    objects.wikidata.append(item)
                    isqx_extras["wikidata"].append(item)
                elif isinstance(item, SymbolDetail):
                    objects.symbols.append(item)
                    isqx_extras["symbols"].append(item)
                elif isinstance(item, EquationDetail):
                    objects.equations.append(item)
                    isqx_extras["details"].append(item)

        # set the parent (if found). would be nice for jinja to also show this
        # but we focus on the frontend vis for now.
        for child_path, parent_path in self.possible_parent_maps.items():
            if child_path in self.objects and parent_path in self.objects:
                child_object_detail = self.objects[child_path]
                child_object_detail.parent = parent_path

        for path, details in self.objects.items():
            if path not in self.definitions:
                continue
            definition = self.definitions[path]
            if not isinstance(v := definition.value, QtyKind):
                continue
            details.unit_si_coherent = serialize_unit_expr(
                v.unit_si_coherent,
                unit_decls=unit_decls,
            )
            if v.tags is not None:
                details.tags = tuple(str(t) for t in v.tags)  # str for now

    def write_objects(self, output_dir: str | Path) -> Path:
        path_resolver = _PathResolver(
            alias_targets=self.alias_targets,
            public_api_candidates=self.public_api_candidates,
        )
        public_definitions = _build_public_unit_paths(
            self.definitions,
            path_resolver,
        )
        unit_decls = build_unit_decl_table(
            {
                path: definition.value
                for path, definition in self.definitions.items()
                if isinstance(definition.value, _ARGS_EXPR)
            },
            public_definitions=public_definitions,
        )
        constants_by_definition_path: dict[str, Quantity] = {}
        for path, definition in self.definitions.items():
            if not isinstance(definition.value, (LazyProduct, *_ARGS_NUMBER)):
                continue
            value = definition.value
            value_str = str(
                value.to_approx() if isinstance(value, LazyProduct) else value
            )
            meta = definition.annotated_metadata
            if meta is None or meta.unit is None:
                logger.warning(
                    f"no unit found for {path} in annotated metadata"
                )
                continue  # dimensionless quantities should be annotated anyways
            constants_by_definition_path[path] = Quantity(
                value=value_str,
                unit=serialize_unit_expr(
                    meta.unit,
                    unit_decls=unit_decls,
                ),
            )

        qty_kinds = _remap_public_api_indexed_dict(
            self.objects,
            path_resolver=path_resolver,
            remap_value=lambda details: _remap_qty_kind_detail(
                details,
                path_resolver,
            ),
        )
        constants = _remap_public_api_indexed_dict(
            constants_by_definition_path,
            path_resolver=path_resolver,
            remap_value=lambda quantity: _remap_quantity(
                quantity,
                path_resolver,
            ),
        )
        units = serialize_unit_decls(unit_decls=unit_decls)

        json_path = Path(output_dir) / "objects.json"
        output_data = {
            "qtyKinds": {
                path: to_dict(details) for path, details in qty_kinds.items()
            },
            "constants": {
                path: to_dict(details) for path, details in constants.items()
            },
            "units": units,
        }
        json_path.parent.mkdir(parents=True, exist_ok=True)
        with open(json_path, "w", encoding="utf-8") as f:
            json.dump(output_data, f)
        logger.info(f"wrote objects to {json_path}")
        return json_path


def write_objects_from_config(
    config_file_path: str,
    output_dir: str | Path | None = None,
) -> Path:
    """Write `objects.json` explicitly after a Zensical docs build.

    `objects.json` used to be emitted as a side effect of the Griffe walk
    performed inside the mkdocstrings rendering path. That was fragile under
    Zensical: each build starts by deleting the whole site directory, while warm
    cached builds may skip the expensive markdown and API extraction stages.
    The build still succeeds, but custom generated artifacts from those skipped
    stages disappear from the final site.

    Zensical currently regenerates a small fixed set of built in artifacts such
    as `objects.inv`, but it does not expose a supported hook for repository
    owned custom non-page artifacts like this file. Therefore `just docs-build`
    must call this helper explicitly after `zensical build` so both cold and
    warm builds deterministically recreate `site/assets/objects.json`.
    """
    from zensical.config import parse_config

    config = parse_config(config_file_path)
    ext_config = _get_extension_config_from_site_config(config)
    extension = IsqxExtension(config=asdict(ext_config))

    root_dir = Path(config_file_path).resolve().parent
    search_paths = [
        str(root_dir.joinpath(path).resolve())
        for path in _get_python_handler_paths(config)
    ]
    loader = GriffeLoader(
        extensions=load_extensions(extension),
        search_paths=search_paths,
    )

    for package_name in _get_top_level_packages(ext_config):
        loader.load(package_name, try_relative_path=False)

    if output_dir is None:
        output_dir = root_dir / config["site_dir"] / "assets"
    assert output_dir is not None
    return extension.write_objects(output_dir)


def _get_extension_config_from_site_config(
    config: Mapping[str, Any],
) -> IsqxExtensionConfig:
    extensions = (
        config.get("plugins", {})
        .get("mkdocstrings", {})
        .get("config", {})
        .get("handlers", {})
        .get("python", {})
        .get("options", {})
        .get("extensions", ())
    )
    for extension in extensions:
        if not isinstance(extension, Mapping):
            continue
        key = "isqx.mkdocs.extension:IsqxExtension"
        if key not in extension:
            continue
        ext_value = extension.get(key)
        ext_config = (
            ext_value.get("config", {})
            if isinstance(ext_value, Mapping)
            else {}
        )
        return IsqxExtensionConfig(
            definitions=tuple(ext_config.get("definitions", ())),
            details=tuple(ext_config.get("details", ())),
        )
    raise ValueError("isqx mkdocstrings extension config not found")


def _get_python_handler_paths(config: Mapping[str, Any]) -> tuple[str, ...]:
    return tuple(
        config.get("plugins", {})
        .get("mkdocstrings", {})
        .get("config", {})
        .get("handlers", {})
        .get("python", {})
        .get("paths", ())
    )


def _get_top_level_packages(
    config: IsqxExtensionConfig,
) -> tuple[str, ...]:
    packages = {
        path.split(".", 1)[0] for path in (*config.definitions, *config.details)
    }
    if not packages:
        raise ValueError("no packages configured for isqx object extraction")
    return tuple(sorted(packages))


def to_dict(obj: Any) -> dict[str, Any]:
    return asdict(obj, dict_factory=lambda x: {k: v for (k, v) in x if v})


class Definition(NamedTuple):
    value: LazyProduct | Number | IsqxExpr | QtyKind
    annotated_metadata: AnnotatedMetadata | None


Definitions: TypeAlias = dict[DefinitionPath, Definition]


#
# public api resolution
#


def _public_api_path_preference_key(path: str) -> tuple[int, int, str]:
    parts = path.split(".")
    private_segments = sum(1 for part in parts[1:] if part.startswith("_"))
    return private_segments, len(parts), path


def _is_public_api_path(path: str) -> bool:
    return all(not part.startswith("_") for part in path.split(".")[1:])


def _build_public_unit_paths(
    definitions: Definitions,
    path_resolver: _PathResolver,
) -> dict[DefinitionPath, PublicApiPath]:
    public_definitions: dict[DefinitionPath, PublicApiPath] = {}
    for path in definitions:
        public_path = path_resolver.to_public_api_path(path)
        if _is_public_api_path(public_path):
            public_definitions[path] = public_path
    return public_definitions


def _collect_alias_candidates(
    *,
    pkg_path: str,
    modules_collection: Any,
    alias_targets: dict[PublicApiPath, DefinitionPath],
    public_api_candidates: dict[DefinitionPath, set[PublicApiPath]],
) -> None:
    # griffe's extension callbacks do not reliably surface wildcard-import
    # aliases such as `isqx.N`, so we do one package-wide pass here.
    # `ModulesCollection` is a Griffe internal type, hence `Any`.
    for module_path, module_obj in modules_collection.members.items():
        if not (
            module_path == pkg_path or module_path.startswith(f"{pkg_path}.")
        ):
            continue
        for member in module_obj.members.values():
            if not isinstance(member, Alias):
                continue
            target_path = _get_alias_definition_path(member)
            if target_path is None:
                continue
            _register_public_api_candidate(
                member.path,
                target_path,
                alias_targets=alias_targets,
                public_api_candidates=public_api_candidates,
            )


def _get_alias_definition_path(alias: Alias) -> DefinitionPath | None:
    if alias.runtime is False:
        return None
    try:
        # griffe stores the immediate hop on `target_path`; multi-hop re-exports
        # only collapse to the real definition via `final_target`.
        return alias.final_target.path
    except Exception:
        try:
            return alias.target_path
        except Exception:
            return None


def _register_public_api_candidate(
    alias_path: PublicApiPath,
    target_path: DefinitionPath,
    *,
    alias_targets: dict[PublicApiPath, DefinitionPath],
    public_api_candidates: dict[DefinitionPath, set[PublicApiPath]],
) -> None:
    alias_targets[alias_path] = target_path
    public_api_candidates.setdefault(target_path, set()).add(alias_path)


_RemappedValueT = TypeVar("_RemappedValueT")


def _remap_public_api_indexed_dict(
    items: Mapping[str, _RemappedValueT],
    *,
    path_resolver: _PathResolver,
    remap_value: Callable[[_RemappedValueT], _RemappedValueT],
) -> dict[PublicApiPath, _RemappedValueT]:
    remapped: dict[PublicApiPath, _RemappedValueT] = {}
    source_paths: dict[PublicApiPath, str] = {}
    for path, value in items.items():
        public_path = path_resolver.to_public_api_path(path)
        existing_source = source_paths.get(public_path)
        if existing_source is not None and existing_source != path:
            raise ValueError(
                "multiple definition paths resolved to the same public API path: "
                f"{existing_source}, {path} -> {public_path}"
            )
        remapped[public_path] = remap_value(value)
        source_paths[public_path] = path
    return remapped


@dataclass(frozen=True)
class _PathResolver:
    alias_targets: Mapping[PublicApiPath, DefinitionPath]
    public_api_candidates: Mapping[DefinitionPath, set[PublicApiPath]]

    def to_definition_path(self, path: str) -> DefinitionPath:
        current = path
        seen: set[str] = set()
        # this remains defensive because unresolved or cyclic aliases can still
        # appear in griffe's graph even though we prefer `final_target.path`
        # when harvesting candidates.
        while current in self.alias_targets and current not in seen:
            seen.add(current)
            current = self.alias_targets[current]
        return current

    def to_public_api_path(self, path: str) -> PublicApiPath:
        definition_path = self.to_definition_path(path)
        if _is_public_api_path(definition_path):
            return definition_path

        public_candidates = [
            candidate
            for candidate in self.public_api_candidates.get(definition_path, ())
            if _is_public_api_path(candidate)
        ]
        if public_candidates:
            return min(public_candidates, key=_public_api_path_preference_key)
        return definition_path


def _remap_fragment(
    fragment: StrFragment,
    path_resolver: _PathResolver,
) -> StrFragment:
    if isinstance(fragment, Anchor):
        return Anchor(
            text=fragment.text,
            path=path_resolver.to_public_api_path(fragment.path),
        )
    return fragment


def _remap_fragment_collection(
    fragments: StrFragment | tuple[StrFragment, ...],
    path_resolver: _PathResolver,
) -> StrFragment | tuple[StrFragment, ...]:
    if isinstance(fragments, tuple):
        return tuple(
            _remap_fragment(fragment, path_resolver) for fragment in fragments
        )
    return _remap_fragment(fragments, path_resolver)


def _remap_where(
    where: Where,
    path_resolver: _PathResolver,
) -> Where:
    return replace(
        where,
        description=_remap_fragment_collection(
            where.description,
            path_resolver,
        ),
        unit=where.unit,
    )


_KaTeXWhereT = TypeVar("_KaTeXWhereT", bound=KaTeXWhere)


def _remap_katex_where(
    detail: _KaTeXWhereT,
    path_resolver: _PathResolver,
) -> _KaTeXWhereT:
    if detail.where is None:
        return detail
    return replace(
        detail,
        where=tuple(
            _remap_where(where, path_resolver) for where in detail.where
        ),
    )


def _remap_qty_kind_detail(
    detail: QtyKindDetail,
    path_resolver: _PathResolver,
) -> QtyKindDetail:
    return replace(
        detail,
        parent=(
            path_resolver.to_public_api_path(detail.parent)
            if detail.parent is not None
            else None
        ),
        unit_si_coherent=detail.unit_si_coherent,
        symbols=[
            _remap_katex_where(symbol, path_resolver)
            for symbol in detail.symbols
        ],
        equations=[
            replace(
                _remap_katex_where(equation, path_resolver),
                assumptions=(
                    tuple(
                        _remap_fragment_collection(assumption, path_resolver)
                        for assumption in equation.assumptions
                    )
                    if equation.assumptions is not None
                    else None
                ),
            )
            for equation in detail.equations
        ],
    )


def _remap_quantity(
    quantity: Quantity,
    path_resolver: _PathResolver,
) -> Quantity:
    return quantity


#
# details
#


def parse_katex_where_static(
    katex_where_rt: HasKaTeXWhere,
    katex_where_st: str | Expr,
) -> tuple[str, ExprDict | None]:
    # working with static analysis is very annoying, we have to handle kwargs
    # and defaults. using a bunch of asserts for now.
    assert isinstance(katex_where_st, ExprCall), katex_where_st
    katex_st = katex_where_st.arguments[0]
    katex_st_value = (
        katex_st.value if isinstance(katex_st, ExprKeyword) else katex_st
    )
    assert isinstance(katex_st_value, str), katex_st_value
    katex_st_value = (
        katex_st_value.removeprefix("'")
        .removeprefix('"')
        .removesuffix("'")
        .removesuffix('"')
        .replace("\\\\", "\\")
    )  # regex is probably better but eh
    if not len(katex_where_st.arguments) > 1:
        return katex_st_value, None
    where_st = katex_where_st.arguments[1]
    where_st_value = where_st
    if isinstance(where_st, ExprKeyword):
        if where_st.name != "where":
            return katex_st_value, None
        where_st_value = where_st.value
    assert isinstance(where_st_value, ExprDict), where_st_value
    assert katex_where_rt.katex == katex_st_value, (
        f"`griffe` skipped an entry!"
        "\nthis can happen in two keys in the dictionary refer to the same "
        "value. check the definitions."
        f"\nruntime value {katex_where_rt.katex}\ndoes not match griffe: {katex_st_value}"
    )
    return katex_st_value, where_st_value


def parse_where(
    key_rt: DetailKey | Callable[..., DetailKey],
    detail_rt: HasKaTeXWhere,
    where_st: ExprDict,
    *,
    self_path: str,
    definitions: Definitions,
    path_resolver: _PathResolver,
    unit_decls: UnitRegistry,
    mut_self_symbols: list[str],
) -> Generator[Where, None, None]:
    if detail_rt.where is None:
        return
    for (w_rt_k, w_rt_v), w_st_v in zip(
        detail_rt.where.items(),
        where_st.values,
    ):
        description = _parse_fragments(w_rt_v, w_st_v, self_path)
        unit_expr: IsqxExpr | None = None
        frags_for_unit_inference = (
            w_rt_v if isinstance(w_rt_v, tuple) else (w_rt_v,)
        )
        frags_st_for_unit_inference = (
            w_st_v.elements
            if isinstance(w_rt_v, tuple) and isinstance(w_st_v, ExprTuple)
            else (w_st_v,)
        )
        for frag, frag_st in zip(
            frags_for_unit_inference,
            frags_st_for_unit_inference,
        ):
            if isinstance(frag, (str, Anchor)):
                continue
            if isinstance(frag, _RefSelf):
                mut_self_symbols.append(w_rt_k)
                if _is_detail_key(key_rt):
                    unit_expr = _get_unit_expr(
                        key_rt,
                        definition_path=path_resolver.to_definition_path(
                            self_path
                        ),
                        definitions=definitions,
                    )
            else:
                unit_expr = _get_unit_expr(
                    frag,
                    definition_path=path_resolver.to_definition_path(
                        _get_fragment_definition_path(frag, frag_st)
                    ),
                    definitions=definitions,
                )
            if unit_expr is not None:
                break

        unit: UnitExprJson | None
        if unit_expr is None:
            unit = None
        else:
            unit = serialize_unit_expr(
                unit_expr,
                unit_decls=unit_decls,
            )

        yield Where(
            symbol=w_rt_k,
            description=description,
            unit=unit,
        )


def _is_detail_key(
    value: DetailKey | Callable[..., DetailKey],
) -> TypeGuard[DetailKey]:
    return isinstance(value, _ARGS_DETAIL_KEY)


def _get_or_init_isqx_extras(attr_target: Attribute) -> dict[str, Any]:
    mkdocstrings = attr_target.extra.setdefault("mkdocstrings", {})
    tmpl = "function" if attr_target.is_function else "attribute"
    mkdocstrings.setdefault("template", f"isqx/{tmpl}.html.jinja")
    isqx: dict[str, Any] = mkdocstrings.setdefault("isqx", {})
    isqx.setdefault("details", [])
    isqx.setdefault("symbols", [])
    isqx.setdefault("wikidata", [])
    return isqx


def _process_katex_where_detail(
    detail_rt: HasKaTeXWhere,
    detail_st: str | Expr,
    key_rt: DetailKey | Callable[..., DetailKey],
    self_path: str,
    definitions: Definitions,
    path_resolver: _PathResolver,
    unit_decls: UnitRegistry,
) -> tuple[SymbolDetail | EquationDetail, list[str]]:
    _katex_st_value, where_st_value = parse_katex_where_static(
        detail_rt, detail_st
    )
    self_symbols: list[str] = []
    where = (
        tuple(
            parse_where(
                key_rt,
                detail_rt,
                where_st_value,
                self_path=self_path,
                definitions=definitions,
                path_resolver=path_resolver,
                unit_decls=unit_decls,
                mut_self_symbols=self_symbols,
            )
        )
        if where_st_value is not None
        else None
    )
    if isinstance(detail_rt, Equation):
        return EquationDetail(
            katex=detail_rt.katex,
            where=where,
            assumptions=(
                tuple(a) if (a := detail_rt.assumptions) is not None else None
            ),
        ), self_symbols
    if isinstance(detail_rt, Symbol):
        return SymbolDetail(
            katex=detail_rt.katex,
            where=where,
            remarks=detail_rt.remarks,
        ), self_symbols
    raise ValueError(f"unknown {type(detail_rt)=}")


def _process_definitions(
    defs_rt: Detail | tuple[Detail, ...],
    defs_st: Expr | str,
    key_rt: DetailKey | Callable[..., DetailKey],
    self_path: str,
    definitions: Definitions,
    path_resolver: _PathResolver,
    unit_decls: UnitRegistry,
) -> Generator[WikidataDetail | SymbolDetail | EquationDetail, None, None]:
    definitions_rt = defs_rt if isinstance(defs_rt, tuple) else (defs_rt,)
    definitions_st = (
        defs_st.elements if isinstance(defs_st, ExprTuple) else (defs_st,)
    )

    for detail_rt, detail_st in zip(definitions_rt, definitions_st):
        if isinstance(detail_rt, Wikidata):
            yield WikidataDetail(qcode=detail_rt.qcode)
        elif isinstance(detail_rt, HasKaTeXWhere):
            item, self_symbols = _process_katex_where_detail(
                detail_rt,
                detail_st,
                key_rt,
                self_path,
                definitions,
                path_resolver,
                unit_decls,
            )
            yield item
            if self_symbols:
                if len(self_symbols) > 1:
                    raise ValueError(
                        f"too many self symbols for {detail_rt.katex=}"
                    )
                yield SymbolDetail(katex=self_symbols[0])
        else:
            raise ValueError(f"unknown {type(detail_rt)=}")


def _process_details_module(
    defs_path: str,
    loader: GriffeLoader,
    definitions: Definitions,
    path_resolver: _PathResolver,
    unit_decls: UnitRegistry,
) -> Generator[
    tuple[str, WikidataDetail | SymbolDetail | EquationDetail], None, None
]:
    details_rt: Details = dynamic_import(defs_path)
    details_st: Attribute = loader.modules_collection[defs_path]
    assert isinstance(details_st.value, ExprDict), details_st

    for (key_st, defs_st), (key_rt, defs_rt) in zip(
        zip(details_st.value.keys, details_st.value.values),
        details_rt.items(),
    ):
        assert isinstance(key_st, (ExprAttribute, ExprName)), key_st
        self_path = key_st.canonical_path
        for item in _process_definitions(
            defs_rt,
            defs_st,
            key_rt,
            self_path,
            definitions,
            path_resolver,
            unit_decls,
        ):
            yield (self_path, item)


def _get_fragment_definition_path(
    frag_rt: WhereValue,
    frag_st: Expr | str,
) -> str:
    if isinstance(frag_rt, (str, Anchor, _RefSelf)):
        raise ValueError("fragment does not reference a definition path")
    assert isinstance(frag_st, (ExprAttribute, ExprName)), (
        "expected value of the where clause to be a reference to a pre-defined "
        f"quantity, but got {frag_st} (an inline expression)\n"
        "= help: define the quantity first and then use it in the where clause"
    )
    return frag_st.canonical_path


def _parse_fragments(
    where_rt: WhereValue, where_st: Expr | str, self_path: str
) -> StrFragment | tuple[StrFragment, ...]:
    if isinstance(where_rt, tuple):
        fragments_rt = where_rt
        fragments_st = where_st.elements  # type: ignore
        parsed_frags = tuple(
            _parse_fragment(rt, st, self_path, i)
            for i, (rt, st) in enumerate(zip(fragments_rt, fragments_st))
        )
        return parsed_frags
    return _parse_fragment(where_rt, where_st, self_path, 0)


def _parse_fragment(
    frag_rt: WhereValue, frag_st: Expr | str, self_path: str, i: int
) -> StrFragment:
    if isinstance(frag_rt, (str, Anchor)):
        return frag_rt
    if isinstance(frag_rt, _RefSelf):
        return Anchor(screaming_to_normal(self_path, i), self_path)
    # RefDetail
    assert isinstance(frag_st, (ExprAttribute, ExprName)), (
        "expected value of the where clause to be a reference to a pre-defined "
        f"quantity, but got {frag_st} (an inline expression)\n"
        "= help: define the quantity first and then use it in the where clause"
    )
    path = frag_st.canonical_path
    return Anchor(screaming_to_normal(path, i), path)


def _get_unit_expr(
    meaning: DetailKey,
    *,
    definition_path: str,
    definitions: Definitions,
) -> IsqxExpr | None:
    if isinstance(meaning, QtyKind):
        return meaning.unit_si_coherent
    elif isinstance(meaning, (Dimensionless, Tagged)):
        return meaning
    elif isinstance(meaning, Scaled):
        # `DetailKey` is wider than `RefDetail` because details can be keyed by
        # logarithmic quantities such as absorbance (`-1 * Log(transmittance)`).
        # for unit inference we keep the expression itself: `kind()` will still
        # classify logarithmic cases as dimensionless, while any future
        # unit-like scaled key will preserve its scaled unit information.
        # TODO: revisit the correctness
        return meaning
    elif isinstance(meaning, (LazyProduct, *_ARGS_NUMBER)):
        definition = definitions.get(definition_path)
        if definition is None:
            logger.warning(f"no definition found for {definition_path}")
            return None
        if definition.annotated_metadata is not None:
            return definition.annotated_metadata.unit
        else:
            logger.warning(f"no unit found for {meaning} in registry")
            return None
    return None


def screaming_to_normal(s: str, i: int) -> str:
    # a better way would be to parse the docstring but that might be too verbose
    normalized = s.split(".")[-1].lower().replace("_", " ")
    return normalized.capitalize() if i == 0 else normalized


def inject_citation_into_docstring(
    obj: Object, agent: Visitor | Inspector
) -> None:
    if not obj.canonical_path.startswith("isqx._citations."):
        return
    # quick hack to put runtime value into the docstring
    doc_str = dynamic_import(obj.path)
    if not isinstance(doc_str, str):
        logger.warning(
            f"expected citation {obj.path} to be a string, got {type(doc_str)}"
        )
        return
    obj.docstring = Docstring(
        doc_str,
        parent=obj,
        parser=agent.docstring_parser,
        parser_options=agent.docstring_options,
    )
